apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ign72ymv5-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:2e23125283fffbe13562d12d4984caa713280def@sha256:4fdb2fbbb7eeca7aebedb0ef6fc1f955c8858bdad7e8ecc219d36cfd53f9587c
          name: container-image
